<figure class="col-xs-12 col-sm-6 col-md-4 col-lg-4"> <a href="[field:arcurl/]" title="[field:title /]" class="pic-link" target="_blank" > <span class="case-hover"> <span class="hover-link"></span> </span> <img src="[field:litpic/]" alt="[field:title /]" /> </a>
        <h4><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a><br />
          <small>关注：[field:click/]℃ / [field:typename/]</small></h4>
      </figure>