<?php
$z[0]=Array("global","",672,698);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",739,766);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",804,834);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",1316,1351);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n      <figure class=\"col-xs-12 col-sm-6 col-md-4 col-lg-4\"> <a href=\"[field:arcurl/]\" title=\"[field:title /]\" class=\"pic-link\" target=\"_blank\" > <span class=\"case-hover\"> <span class=\"hover-link\"></span> </span> <img src=\"[field:litpic/]\" alt=\"[field:title /]\" /> </a>\r\n        <h4><a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</a><br />\r\n          <small>关注：[field:click/]℃ / [field:typename/]</small></h4>\r\n      </figure>\r\n      ",12695,13228);
$z[4][4]=array();
$z[4][4]['titlelen']="45";
$z[4][4]['row']="6";
$z[4][4]['typeid']="5";
$z[4][4]['flag']="p";
$z[5]=Array("type","\r\n      <p style=\"text-center\"><a href=\"[field:typelink /]\" class=\"btn btn-success\" target=\"_blank\" title=\"查看更多案例\">查看更多 MORE→</a></p>\r\n      ",13269,13466);
$z[5][4]=array();
$z[5][4]['typeid']="5";
$z[6]=Array("arclist","\r\n      <figure class=\"col-xs-12 col-sm-6 col-md-6 col-lg-6\">\r\n        <article class=\"ny-news\"> <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"pull-left pic-link visible-lg\"> <span class=\"case-hover\"> <span class=\"hover-link\"></span> </span> <img src=\"[field:litpic/]\" alt=\"[field:title /]\"> </a>\r\n          <h4><a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\">[field:title /] </a></h4>\r\n          <p>[field:description function=\"cn_substr(@me,120)\"/]…</p>\r\n          <p><span class=\"fl\"><a href='[field:typeurl/]' target=\"_blank\">[field:typename/]</a></span><span class=\"gz\">[field:click/] ℃</span><span class=\"sj\">[field:pubdate function=\"GetDateMK(@me)\"/]</span></p>\r\n        </article>\r\n      </figure>\r\n      ",14640,15450);
$z[6][4]=array();
$z[6][4]['titlelen']="45";
$z[6][4]['row']="6";
$z[6][4]['typeid']="11";
$z[6][4]['flag']="p";
$z[7]=Array("type"," <p class=\"text-center\"><a href=\"[field:typelink /]\" class=\"btn btn-success\" target=\"_blank\" title=\"查看更多新闻\">查看更多 MORE→</a></p>",15495,15678);
$z[7][4]=array();
$z[7][4]['typeid']="11";
$z[8]=Array("include","",15706,15741);
$z[8][4]=array();
$z[8][4]['filename']="foot.htm";

?>